siteName: Veteran Roll Call
tagline: Connecting Veterans with Resources
logoSmall: images/general-elements/veteranrollcall_sm.png
logoFooter: images/general-elements/veteranrollcall_md.png

favicon:
  icon: images/general-elements/favicon/favicon.png
  apple: images/general-elements/favicon/apple-touch-icon.png
  apple72: images/general-elements/favicon/apple-touch-icon-72x72.png
  apple114: images/general-elements/favicon/apple-touch-icon-114x114.png

seo:
  author: Veteran Roll Call
  description: Veteran Roll Call is a trusted resource for veterans, service members, and their families—find programs, VA benefits guidance, and community support.
  keywords: veterans, veteran resources, veteran programs, military families, veteran support, VA benefits, veteran community, veteran services, veteran assistance, veteran administration assistance, VA assistance, veteran outreach

socialLinks:
  - icon: twitter
    label: Twitter
    url: https://twitter.com/veteranrollcall
  - icon: facebook
    label: Facebook
    url: https://facebook.com/veteranrollcall
  - icon: youtube
    label: YouTube
    url: https://youtube.com/@veteranrollcall
  - icon: instagram
    label: Instagram
    url: https://instagram.com/veteranrollcall

menu:
  - label: Home
    url: /
  - label: About Us
    url: /about/
  - label: Programs
    url: /programs/
  - label: Resources
    url: /resources/
  - label: News
    url: /news/
    children:
      - label: Articles
        url: /news/articles/
      - label: Updates
        url: /news/updates/
  - label: Get Involved
    url: /get-involved/
  - label: Donate
    url: /donate/
  - label: Contact
    url: /contact/
